version: '3.3'
services:
  api:
    container_name: 'api'
    restart: unless-stopped
    build: './'
    ports:
      - '8080:8080'
    volumes:
      - './:/go/src/app'
    depends_on:
      - 'mongo'
    command: bash -c "app"    
  mongo:
    image: 'mongo:latest'
    container_name: 'mongo'
    ports:
      - '27100:27017'
